### PR TITLE
Update naming-convention.md

### PR DESCRIPTION
**Pull request by bradleyayers**
Remove extraneous array wrapping.

### CODE REVIEW

**Comment by dotansimha** [comment]
Hi @bradleyayers ! 
Our documentation is generated automatically based on the JSON schema defined in each rule, so the documentation schema for this specific rule is coming from here: https://github.com/dotansimha/graphql-eslint/blob/master/packages/plugin/src/rules/naming-convention.ts#L148 

I assume this was opened because you had an issue with the generated example? Can you please elaborate on this? 

Thanks!

**Comment by bradleyayers** [comment]
Hey @dotansimha, so the problem is that the example is wrong (it's invalid if you try to actually use it):

Instead of

```json
["error", [{"ObjectTypeDefinition":"PascalCase"}]]
```

it should be

```json
["error", {"ObjectTypeDefinition":"PascalCase"}]
```

So it sounds like there's an issue with the generator.

**Comment by B2o5T** [comment]
@dotansimha I fixed JSON schema in this PR https://github.com/dotansimha/graphql-eslint/pull/411 so you can close this one because @bradleyayers fixed markdown code and not source code

**Comment by dotansimha** [comment]
Fixed in https://github.com/dotansimha/graphql-eslint/pull/411

**Pull request closed without merging**
