### PR TITLE
feat: remove `prettier` rule, add related docs

### LINKED ISSUE #395: deprecate rule `prettier` since `eslint-plugin-prettier` itself supports virtual filenames correctly now
See

https://github.com/prettier/eslint-plugin-prettier/pull/401/files#diff-e9a90fe7b2d3420b8e5f64e24d5f56ffe6383e47b07461172cc29ed21b768905R197-R199

and

https://github.com/prettier/eslint-plugin-prettier/blob/master/eslint-plugin-prettier.js#L192-L209

---

Besides, actually it is supported previously too. All the user need to do is like the following:

```js
module.exports = {
  // ...
  overrides: [
    {
      files: '*.graphql', // it includes virtual filenames like `*.js/0_document.graphql` already
      rules: {
        'prettier/prettier': [
          2,
          {
            parser: 'graphql',
          },
        ],
      },
    },
  ],
}
```

<del>
After `eslint-plugin-prettier@3.4.0`, the above configuration is not needed any more too!
</del>

Maybe in `eslint-plugin-pretter@3.5.0` after https://github.com/prettier/eslint-plugin-prettier/pull/413 and https://github.com/prettier/eslint-plugin-prettier/pull/415 been merged and released.

### PR DESCRIPTION
**Pull request by JounQin**
🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #395

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

N/A

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] `examples/prettier`

**Test Environment**:
- OS: macOS
- `@graphql-eslint/eslint-plugin`: 0.9.1
- NodeJS: 14.16

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests and linter rules pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dotansimha** [comment]
This is great, thank you @JounQin ! 
Can you please just rebase your PR and then we can get this merged?

**Review by dotansimha — APPROVED** [review]

**Comment by JounQin** [comment]
@dotansimha Done!

**Comment by B2o5T** [comment]
@JounQin i think you definitely must add `*.ts/*.graphql` to override object for turn off `prettier/prettier` rule

**Comment by JounQin** [comment]
@B2o5T Oh, right, I'll add `.jsx/.tsx` too soon.

**Review by dotansimha — APPROVED** [review]

**Comment by dotansimha** [comment]
Thank you @JounQin . I'm merging this one, but might take a few days to release, since I want to bump a major in this one, and I plan to squeeze in a few more change for v1.

**Pull request merged**
